### ISSUE TITLE
Bearbeitung und Löschfunktion bei Fahrzeugen 

### ISSUE THREAD

**Issue by Bema2** [Steet1Net/Baustelle.py#11]
Sodass man fahrzeuge bearbeiten und löschen kann

zum beispiel namen ändern wenn schon erstellt

**Comment by Steet1Net** [comment]
kann bearbeitet werden

**Comment by Steet1Net** [comment]
Löschfunktion für Fahrzeuge wurde mit Passwortabfrage hinzugefügt.
