### ISSUE TITLE
Kran Symbol 

### ISSUE THREAD

**Issue by Bema2** [Steet1Net/Baustelle.py#14]
Kran symbol bei baustellen ändert sich soll gleich sein 

![Bei_Daschboard](https://github.com/Steet1Net/Baustelle.py/assets/169804141/5780d915-32c1-4200-9e42-133a533b8f3f)
![Bei_allem anderen](https://github.com/Steet1Net/Baustelle.py/assets/169804141/23af5c19-8fd5-4940-abb2-b078a0c93f95)

Symbol wird wenn man auf Dashboard geht normal angezeigt und bei Fahrzeuge und neu wird es rot angezeigt

**Comment by Steet1Net** [comment]
behoben
