### ISSUE TITLE
Sinnvolle Baustellen- und Fahrzeugnamen

### ISSUE THREAD

**Issue by FLOL01** [Steet1Net/Baustelle.py#7]
Die Bestehenden Baustellen und Fahrzeuge sinnvoll umbenennen und neue Fahrzeuge / Baustellen von vorne rein sinnvoll benennen.

Eventuell ein Schema einführen?

**Comment by Steet1Net** [comment]
es werden kennzeichen als fahrzeugnamen verwendet
